# Site settings
title: Acid Child
email: your-email@domain.com
url: https://example.github.io
description: "Acid Child"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Acid Child

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://twitter.com/SBootstrap
  - title: facebook
    url: https://www.facebook.com/acidchildband

# Build settings
markdown: kramdown
permalink: pretty
